version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: private-lender-api/server:latest
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
  mongodb:
    image: mongo:5.0.9
    ports:
      - "27017:27017"
